== Pong, Restructured

In the _SNAKE_ tutorial, we did the entire game inside of one main function. That's fine for short games, but it becomes more and more problematic the longer your game gets.

This time around, we're going to organize our game in a way that will be much more intuitive. By splitting our one big function into lots of smaller ones, it'll be easier to organize our thoughts and understand the logic of our game as we expand it.

Which is... AWESOME!

=== Instructions

==== If a Pong Ball's in a Forest...

Let's take a moment to think about the _defining essence_ of our game.

This is a pong game, so what does a pong game need? In the last section, we made a nice list to answer that question.

// picture of ping pong table would be nice.

- A table
- A ball
- Two paddles
- A score board

Now, that's what a pong game has in it, but what about gameplay? What _happens_ in the game?

- There's a field; it just sits there
- Either player can move a paddle up or down
- A ball bounces around the screen
  - If it hits a paddle, it bounces back the other way
  - If it goes the past paddle, the other player scores a point, and the field resets
- First one to 9 points wins, and the game starts over
- The opponent in our game will be a computer
- Everything needs to be drawn to the screen

That's everything that happens in our game, so that's how we should organize it.

==== Setup and Go

A pattern you will commonly see when programming is a setup / run cycle. That is:

- A *setup* phase where all the key variable and starting conditions for the program are set.
- A *run* phase where the program continues to operate based on your parameters.

It's kind of like playing with dominoes. You _set up_ all the dominoes, then *run away* when they all start falling down (lol).

We had setup and run code in _SNAKE_, but we did it haphazardly just when we needed it. Now we're going to do it for real.

===== Step 1: Adding the game loop

Let's move what we have into a running loop. Having your game loop in a separate function means you can use the same game code with different starting circumstances.

We'll throw a `gfx.Clear` in there too because we'll need one as soon as things start moving.

[source]
.HelloPong.spin
----
PUB Main
    lcd.Start(gfx.Start)
    ctrl.Start
    
+++    repeat
+++        RunGame
+++    
+++PUB RunGame
+++
+++    gfx.Clear

    repeat i from 0 to 7
        gfx.Sprite (@centerline_gfx, 63, i*8, 0)
    
    gfx.Sprite (@ball_gfx, 60, 28, 0)
----

===== Step 2: Making a draw function



[source]
.HelloPong.spin
----
PUB RunGame

    gfx.Clear
+++    
+++    DrawGame
+++
+++    lcd.Draw
+++
+++PUB DrawGame

    repeat i from 0 to 7
        gfx.Sprite (@centerline_gfx, 63, i*8, 0)

    gfx.Sprite (@ball_gfx, 60, 28, 0)
    gfx.Sprite (@paddle_gfx, 4, 24, 0)
    gfx.Sprite (@paddle_gfx, 116, 24, 0)
---    
---    lcd.Draw

DAT

    ball_gfx
----



To create our game setup, let's create