== Pong, Restructured

In the _SNAKE_ tutorial, we did the entire game inside of one main function. That's fine for short games, but it becomes more and more problematic the longer your game gets.

This time around, we're going to organize our game in a way that will be much more intuitive. By splitting our one big function into lots of smaller ones, it'll be easier to organize our thoughts and understand the logic of our game as we expand it.

Which is... AWESOME!

=== Instructions

==== If a Pong Ball's in a Forest...

Now, before we add graphics and start building out our game, let's take a moment to think about the _defining essence_ of our game.

This is a pong game, so what does a pong game need? In the last section, we made a nice list to answer that question.

// picture of ping pong table would be nice.

- A table
- A ball
- Two paddles
- A score board

Now, that's what a pong game _has_, but what about gameplay? What _happens_ in the game?

- There's a field; it just sits there
- Either player can move a paddle up or down
- A ball bounces around the screen
  - If it hits a paddle, it bounces back the other way
  - If it goes the past paddle, the other player scores a point, and the field resets
- First one to 9 points wins, and the game starts over
- The opponent might be a computer

That's pretty much it. That's everything that happens in our entire game, so that's how we should organize it.

==== Loop de loop

First and foremost, everything that happens in our game needs to happen in a loop. Loops are the magic that makes the world go round.

[source]
.HelloPong.spin
----
PUB Main
    lcd.Start(gfx.Start)
    ctrl.Start
+++    
+++    repeat
+++        GameLoop
+++        
+++PUB GameLoop
+++
----
